---
title: "Colour Name & Hex code"
output: 
 html_document:
   code_folding: hide
   code_download: TRUE
   theme: readable
   
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=TRUE, warning=TRUE, include=FALSE}
library(dplyr)
library(knitr)
library(kableExtra)
library(tidyverse)
library(DT)
```


```{r echo=FALSE}

colourdata <- data.frame(
  colourname = colors(),
  hex_code   = rgb(t(col2rgb(colors())), maxColorValue = 255)
)


```



```{r echo=FALSE, message=FALSE, warning=FALSE}

# Create styled HTML cell
datatable_data <- colourdata %>%
  mutate(colour = paste0(
    '<div style="background-color:', hex_code,
    '; color:white; padding:5px; border-radius:4px;">',
    colourname, '</div>'
  ))


datatable(
  datatable_data,
  escape = FALSE,
  filter = "top",
  rownames = FALSE,
  editable = FALSE,
  extensions = c("Buttons", "Scroller", "Responsive", "KeyTable", "SearchBuilder","RowReorder"),
  options = list(
    rowReorder = TRUE,
    keys = TRUE,
    scrollY = 600,
    scrollX = 200,
    responsive = FALSE,
    pageLength = 10,
    lengthMenu = c(10, 25, 50,100),
    dom = 'QBlfrtip',  # ✅ Q = SearchBuilder, B = Buttons
    searchBuilder = TRUE,
    buttons = c('copy', 'csv', 'pdf', 'print')
  )
)


```


This code is used to select the specific colour by using hex code 
you use filter options inbetween for better selection 



Viewing this in a datatable structure

